### PR TITLE
Support external bugs link

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
I'm not sure supporting custom include fields is relevant, perhaps the function could be renamed getBugAll by forcing the value to `_all`. You can check the api using this bug for example:

```haskell
AnonymousSession <$> newBugzillaContext "bugzilla.redhat.com" >>= \sess -> getBugIncludeField sess 1791815 "_all"
```

**Comment by juhp** [comment]
I haven't tried yet (I didn't know bugzilla had this - I actually have wanted such functionality!)
but the fieldname `include_fields` suggests it might support a (comma-separated?) list of fields?
Or am I misunderstanding how to use this?

**Comment by TristanCacqueray** [comment]
Unfortunately this isn't well documented, using `_all` seems to be the only way to get the external bugs "field". I guess it would be better to hardcode the query arg similarly to the `searchBugsAll` using a `getBugAll` function instead.

**Comment by juhp** [comment]
Okay, right, though `include_fields` can also be used to select other specific standard fields, right.

+1 for `getBugAll`

Should `getBugIncludeField` be renamed to `getBugIncludeFields`?

**Comment by TristanCacqueray** [comment]
Alright, last update use `getBugIncludeFields` and provide `getBugAll`, e.g.:

```haskell
sess <- AnonymousSession <$> newBugzillaContext "bugzilla.redhat.com"
Just b1 <- getBugIncludeFields sess 1791815 ["_all"]
Just b2 <- getBugAll sess 1791815
b1 == b2
```

**Comment by juhp** [comment]
Thanks, I will merge this.

It would be nice to have a testsuite some day.

**Comment by juhp** [comment]
I can probably make a release soon to include all your recent PRs.

**Comment by TristanCacqueray** [comment]
Thank you for the prompt feedback. I don't mind using a local cabal.project to pull in the changes, and I should be able to add test soon, so a new release can wait.

**Comment by TristanCacqueray** [comment]
Actually, `getBugIncludeFields` raises BugzillaJSONParseError when the set of fields is a subset of the current `Bug` record. I think it should not be exposed: https://github.com/juhp/hsbugzilla/pull/10

**Comment by juhp** [comment]
Ah right, of course, hmm - that's why there is `BugID`...

**Pull request merged**
